name: news_list
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  flutter_localizations:
    sdk: flutter

  intl: ^0.18.1

  json_annotation: ^4.8.1

  url_launcher: ^6.2.5

  flutter_bloc: ^8.1.4

  get_it: ^7.6.7

  dio: ^5.4.2
  pretty_dio_logger: ^1.3.1

  cupertino_icons: ^1.0.2

  auto_route: ^7.8.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1
  flutter_lints: ^2.0.0
  build_runner: ^2.4.8
  auto_route_generator: ^7.3.2

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins.ttf


flutter_intl:
  enabled: true
  class_name: AppLocalization
  main_locale: ru